cursopython/Tema12/directores/directores/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from peliculas import views


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.index, name='index'),
    path('', include('peliculas.urls')),
]

cursopython/Tema12/directores/peliculas/urls.py
from django.urls import path
from . views import genero, index
from . import views

urlpatterns = [
  path('', index, name='admin-index'),
  path('', views.IndexView.as_view(), name='directores'),
  path('', views.DirectorView.as_view(), name='director'),
  path('', views.peliculas, name='pelicula'),
  path('', views.genero, name='genero'),
]

cursopython/Tema12/directores/peliculas/models.py
from django.db import models

# Create your models here.

class Director(models.Model):
    nombre = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)   
    fecha_de_nacimiento = models.DateField(null=True, blank=True)
    fecha_finado= models.DateField(null=True, blank=True)
    biografia = models.TextField()
    imagen = models.URLField(max_length=200, null=True)
    
    def __str__(self):
        return '%s %s' % (self.nombre, self.apellidos)
    
class Genero(models.Model):
    name = models.CharField(max_length=64, help_text="Nombre del Genero")
    
class Pelicula(models.Model):
    titulo = models.CharField(max_length=32)
    director = models.ForeignKey(Director, on_delete=models.SET_NULL, null=True)
    resumen = models.TextField(max_length=100, help_text='Sinopsis de Pelicula')
    genero = models.ManyToManyField(Genero)
    duracion = models.PositiveIntegerField()
    imagen = models.URLField(max_length=200, null=True)
    
    def __str__(self):
        return self.titulo

cursopython/Tema12/directores/peliculas/views.py
from django.shortcuts import render
from django.views import generic

from .models import Director, Pelicula, Genero


    
def index(generic.ListView):
    
        
        template_name = 'directores.html'
        model = Director 
        
         


class DirectorView(generic.DetailView):
    template_name = 'director.html'
    model = Director

class PeliculaView(generic.DetailView):
    template_name = 'pelicula.html'
    model = Pelicula
    
def peliculas(request):
    return render(
        request,
        'pelicula.html'
    )
    
class Genero(generic.ListView):
    model = Genero
    
    
def genero(request):
    return render(
        request,
        'genero.html'
        )

cursopython/Tema12/directores/peliculas/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>

    {% block title %}<title>Peliculas</title>{% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>

{% load static %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
   <div class="container-fluid bg-primary">

    <div class="row">

        <div class="col-sm-8"><br>
            
            {% block header %}
                
            {% endblock %}
                
        </div>


        <div class="col-sm-4">        
            {% block sidebar %}<br>
            <div class="btn-group">
                <a type="button" class="btn btn-primary" href="{% url 'directores' %}">Inicio</a>
                <a type="button" class="btn btn-primary" href="{% url 'pelicula' %}">Peliculas</a>
                <a type="button" class="btn btn-primary" href="{% url 'director' %}">Director</a>
                <a type="button" class="btn btn-primary" href="{% url 'genero' %}">Generos</a>
            </div>
        </div>
            
            {% endblock %}
                
        
    </div>
   </div>

   <div class="container-fluid">
    <div class=row>
        
        {% block content %}
            
        {% endblock %}
            
    </div>
   </div>


</body>
</html>

cursopython/Tema12/directores/peliculas/templates/director.html
{% extends "peliculas/base.html" %}

{% block title %}Director - {{ director }}{% endblock %}

{% block header-title %}{{ director }}{% endblock %}

{% block content %}
<img class="detalle" src="{{ director.imagen }}" alt="Foto de {{ director }}" ><br>
<p>{{ director.fecha_nacimiento}} - {{director.fecha_defuncion | default_if_none:""}}</p>
<h4>Biografía</h4>
<p>{{ director.biografia | linebreaks }}</p>
<h4>Peliculas</h4>
<table>
    <tr>
    {% for pelicula in director.pelicula_set.all %}
        <td onclick="window.location.href='/pelicula/{{pelicula.id}}'">
            <img src="{{ pelicula.imagen }}" alt="Portada de {{ pelicula }}"><br>
            <span class="nombre_pelicula">{{ pelicula }}</span>
        </td>
        {% cycle '' '' '</tr><tr>' %}
    {% empty %}
        <td>No hay peliculas aún</td>
    {% endfor %}
    </tr>
</table>
{% endblock %}

cursopython/Tema12/directores/peliculas/templates/directores.html
{% extends "base.html" %}

{% block title %}Directores{% endblock %}


{% block content %}
<table>
    <tr>
    {% for director in object_list %}
        <td onclick="window.location.href='/{{director.nombre}}'">
            <img src="{{ director.imagen }}" alt="Foto de {{ director }}"><br>
            <span class="nombre_director">{{ director }}{% if director.fecha_defuncion %}&dagger;{% endif %}</span>
        </td>
        {% cycle '' '' '</tr><tr>' %}
    {% empty %}
        <td>No hay directores aún</td>
    {% endfor %}
    </tr>
</table>
{% endblock %}

cursopython/Tema12/directores/peliculas/templates/genero.html
{% block heder %}
   <title>Generos</title>
{% endblock heder %}
    


{% block content %}
    <p>Estos son los generos</p>
{% endblock content %}
    

cursopython/Tema12/directores/peliculas/templates/pelicula.html
{% extends "peliculas/base.html" %}

{% block title %}Pelicula - {{ pelicula }}{% endblock %}

{% block header-title %}{{ pelicula }}{% endblock %}

{% block content %}
<img class="detalle" src="{{ pelicula.imagen }}"
  alt="Portada de {{ pelicula }}"><br>
<p><b>Año: </b>{{ pelicula.año}}</p>
<h4>Sinopsis</h4>
<p>{{ pelicula.sinopsis | linebreaks }}</p>
{% endblock %}